# Copyright (c) 2017 Advanced Micro Devices, Inc. All rights reserved.
#
# This file is made available under a 3-clause BSD license.
# See tools/LICENSE for licensing details.

all:

clean:
	rm -f $(THIS_TOOL_DIR)*.csv $(THIS_TOOL_DIR)*.dat $(THIS_TOOL_DIR)*.txt
